"""initial_schema

Revision ID: 544ca4dbe20f
Revises: 
Create Date: 2026-03-07 01:20:59.148580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '544ca4dbe20f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dish_name_master',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('cuisine_type', sa.String(length=20), nullable=False),
    sa.Column('pattern_suffix', sa.String(length=20), nullable=True),
    sa.Column('typical_ingredients', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('typical_ingredient_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('popularity_score', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredient_master',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('default_unit', sa.String(length=20), nullable=True),
    sa.Column('icon_url', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_core',
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('dish_name', sa.String(length=200), nullable=False),
    sa.Column('base_servings', sa.Integer(), nullable=False),
    sa.Column('base_servings_source', sa.String(length=20), nullable=False),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cooking_time_min', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.String(length=10), nullable=True),
    sa.Column('raw_transcript', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('prompt_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_type', 'source_id', name='uq_recipe_core_source')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_id', sa.String(length=255), nullable=True),
    sa.Column('default_servings', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('youtube_channels',
    sa.Column('channel_id', sa.String(length=50), nullable=False),
    sa.Column('channel_name', sa.String(length=200), nullable=False),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('subscriber_count', sa.BigInteger(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id')
    )
    op.create_table('youtube_video_snapshot',
    sa.Column('video_id', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('yt_channel_id', sa.String(length=50), nullable=True),
    sa.Column('channel_name', sa.String(length=200), nullable=True),
    sa.Column('view_count', sa.BigInteger(), nullable=True),
    sa.Column('like_count', sa.BigInteger(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id'),
    comment='YouTube API metadata - 30day TTL (expires_at)'
    )
    op.create_table('channel_video_index',
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description_text', sa.Text(), nullable=True),
    sa.Column('has_recipe_in_desc', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tsv_title', postgresql.TSVECTOR(), nullable=True),
    sa.Column('tsv_description', postgresql.TSVECTOR(), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['youtube_channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id'),
    comment='YouTube API data - 30day TTL (expires_at)'
    )
    op.create_index(op.f('ix_channel_video_index_channel_id'), 'channel_video_index', ['channel_id'], unique=False)
    op.create_table('recipe_core_ingredients',
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=True),
    sa.Column('raw_name', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('scaling_strategy', sa.String(length=20), nullable=False),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient_master.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe_core.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_recipes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('recipe_core_id', sa.UUID(), nullable=False),
    sa.Column('custom_servings', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_core_id'], ['recipe_core.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_history',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('search_type', sa.String(length=20), nullable=False),
    sa.Column('detected_dish_id', sa.UUID(), nullable=True),
    sa.Column('detected_ingredients', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('servings', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=True),
    sa.Column('channel_filter', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['detected_dish_id'], ['dish_name_master.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_favorite_channels',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['youtube_channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'channel_id', name='uq_user_channel')
    )
    op.create_index(op.f('ix_user_favorite_channels_user_id'), 'user_favorite_channels', ['user_id'], unique=False)
    op.create_table('user_ingredients',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient_master.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_ingredients_user_id'), 'user_ingredients', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_ingredients_user_id'), table_name='user_ingredients')
    op.drop_table('user_ingredients')
    op.drop_index(op.f('ix_user_favorite_channels_user_id'), table_name='user_favorite_channels')
    op.drop_table('user_favorite_channels')
    op.drop_table('search_history')
    op.drop_table('saved_recipes')
    op.drop_table('recipe_core_ingredients')
    op.drop_index(op.f('ix_channel_video_index_channel_id'), table_name='channel_video_index')
    op.drop_table('channel_video_index')
    op.drop_table('youtube_video_snapshot')
    op.drop_table('youtube_channels')
    op.drop_table('users')
    op.drop_table('recipe_core')
    op.drop_table('ingredient_master')
    op.drop_table('dish_name_master')
    # ### end Alembic commands ###
